apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: staging
spec:
  kind: Permanent
  label: Staging
  namespace: eks-test-staging
  order: 100
  previewGitInfo:
    user: {}
  promotionStrategy: Auto
  source:
    url: https://github.com/explore-jenkinsx/environment-roarerspring-staging.git
  teamSettings:
    defaultScheduler:
      kind: ""
      name: ""
status: {}
