# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml

PipelineSecrets:

  # lets enable ECR docker builds
  DockerConfig: |-
    {
      "credsStore": "ecr-login"
    }
    
docker-registry:
  enabled: false    
nexus:
  enabled: false

auth:
  git:
    username: jx-bot-demo
build:
  enabled: false
buildnum:
  enabled: false
pipelinerunner:
  enabled: "true"
tillerNamespace: ""
